# Generated by Django 5.1.1 on 2024-10-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retete', '0005_categorie_recipient_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipient',
            name='categ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retete.categorie'),
        ),
    ]
