# Generated by Django 5.1.1 on 2024-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retete', '0006_savedrecipient_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipient',
            name='categ',
        ),
        migrations.AddField(
            model_name='recipient',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='retete_imagini/'),
        ),
    ]
